### PR TITLE
Some changes for better portability

### PR DESCRIPTION
**Pull request by chronos-tcs**
Hi, loved the idea! Had to nake some changes to work in my server, since I'm using entware python is in weird place below /opt, also my backups organize my backups in subdirectories.

Also I created a config file so is easier to update and test.

### CODE REVIEW

**Comment by EgonSpengler** [comment]
Hey, thanks for the excellent changes!  I haven't used ConfigParser myself, so my only question is this: if a less tech-savvy person downloads this to run and just changes the config settings, will ConfigParser look for the .template file in case it cannot find config.ini and use those?  Or is the user responsible for also saving it as config.ini?

**Comment by chronos-tcs** [comment]
The way I made, at least for now, the user must copy `config.ini.template` to `config.ini` and edit.
Now that you ask I should've updated the README.md, I know very little of python, but shoud be easy to make a check if the file exists, if not copy the template, I will take a look into that tomorrow

**Comment by EgonSpengler** [comment]
I know only a little of python myself, which is why I asked ;)

Alternatively, the file could simply be renamed to config.ini since it's expected that the user will have to make their own changes anyway.

**Comment by chronos-tcs** [comment]
> Alternatively, the file could simply be renamed to config.ini since it's expected that the user will have to make their own changes anyway.

That would defeat the purpose, see, let's say you made some changes to the script, if I wanted to update I just run  `git pull https://github.com/EgonSpengler/nspjson.git` and since config.ini is on the `.gitignore` it's safe and not affected by that.
And there is no risk any of us accidentally push private info, I know there is nothing to be worry here, but I'm kind of a security paranoid 😅

**Comment by EgonSpengler** [comment]
Fair enough!  I'll merge the pull request as-is tomorrow and update the readme with a sentence or two.

**Pull request merged**
